- lib/debug_views/debug_page.dart
- lib/debug_views/globals.dart
- lib/main.dart
- close #24 
- 
- 
- 
- 
- 
- 
- 
Before | After
:--: | :--:
チェックした人：
> repositoryの動作確認をするためのdebugページの作成

- README.md
- pubspec.lock
- pubspec.yaml
- close #27 
- 
- 
- 
- 
- 
- 
- 
Before | After
:--: | :--:
チェックした人：
> flutterのversion固定

- analysis_options.yaml
- lib/debug_views/debug_page.dart
- lib/debug_views/globals.dart
- lib/debug_views/organization_dialog.dart
- lib/debug_views/user_dialog.dart
- lib/models/converter/converter.dart
- lib/models/converter/holiday_converter.dart
- lib/models/converter/user_converter.dart
- lib/models/holiday/holiday.dart
- lib/models/holiday/holiday.freezed.dart
- lib/models/holiday/holiday.g.dart
- lib/models/models.dart
- lib/models/organization/organization.dart
- lib/models/organization/organization.freezed.dart
- lib/models/organization/organization.g.dart
- lib/models/user/user.dart
- lib/models/user/user.freezed.dart
- lib/models/user/user.g.dart
- lib/repositories/interfaces/organization_repository_interface.dart
- lib/repositories/mocks/organization_repository_mock.dart
- lib/repositories/mocks/user_repository_mock.dart
- lib/repositories/organization_repository.dart
- lib/repositories/user_repository.dart
- close #16 
- 
fire storeに作られるデータ構造が良いかどうか確認してほしい．
repositoryに必要な機能は今後追加していくということで最低限のCreate, Get, Updateを作成しました．
- organization repositoryのinterface, mock, implementationを追加
- repositoryの動作確認を行うためのdebug pageの追加
- debug pageのファイル分割
- organization createで指定したIDの組織が追加される．
- organization getで指定したIDの組織の情報がデバッグコンソールに表示される．
- organizations getで現在ログインしているuserがownerになっている組織の一覧がデバッグコンソールに表示される．
- organization updateで指定したIDの組織の定休日が追加されている(updateの確認)
Before | After
:--: | :--:
チェックした人：
> 組織のデータ構造とリポジトリの実装

- .github/workflows/test_and_build.yml
- firebase/Dockerfile
- firebase/docker-compose.yml
- firebase/firebase.json
- close #41 
- 
firebaseのemulatorをdockerizeして，
GitHubActionsでfirebaseのテストを行うように記述
- 
- 
- 
```sh
$ cd firebase
$ npm i
$ docker-compose up -d
$ npm test
```
でテストが実行されることを確認する．
Before | After
:--: | :--:
チェックした人：
> CIでfirebaseのルールのテストを行う

- lib/pages/setting/setting_account_item.dart
- lib/pages/setting/setting_list_item.dart
- lib/pages/setting/setting_page.dart
- なし
- masterブランチマージ後に、appbarが無くなってしまったため追加。
- appbarの追加
- ボタン押下時のデバック処理追加・修正
Before | After
:--: | :--:
チェックした人：
> [設定画面]appbarの追加

- lib/debug_views/debug_page.dart
- lib/debug_views/globals.dart
- lib/debug_views/shift_dialog.dart
- lib/models/models.dart
- lib/models/shift/shift.dart
- lib/models/shift/shift.freezed.dart
- lib/models/shift/shift.g.dart
- lib/repositories/interfaces/shift_repository_interface.dart
- lib/repositories/mocks/shift_repository_mock.dart
- lib/repositories/shift_repository.dart
- close #15
- 
シフト情報を取得するRepositoryの作成
それを確認するデバッグページの作成
- 
- 
- 
- ログインなどを行った後に
- shift create, update, delete操作をすることでfiresotoreにそれぞれのデータが格納されていることを確認する.
- shift list getでデバッグコンソールにデータベースの情報がprintされていることを確認する．
updateも同じ入力方法
create後のデータベース
チェックした人：
> シフト情報の構造とリポジトリの作成

- lib/repositories/shift_repository.dart
- close #53 
- 
getDocumentを31日分するところと
結果をMap化するところを分けることでうまく非同期的に処理を行い応答速度を時短した．
- 
- 
- 
- 
- 
- 
Before | After
:--: | :--:
チェックした人：
> getShiftsの応答速度

- .github/workflows/test_and_build.yml
- README.md
- lib/main.dart
- lib/models/shift/shift.freezed.dart
- lib/models/shift/shift.g.dart
- lib/pages/calendar/calendar_state.dart
- lib/pages/calendar/calendar_state.freezed.dart
- lib/pages/calendar/widgets/calendar_list_item_widget.dart
- lib/pages/calendar/widgets/calendar_list_widget.dart
- lib/pages/calendar/widgets/calendar_widget.dart
- lib/pages/calendar/widgets/marker_widget.dart
- lib/pages/setting/setting_account_item.dart
- lib/pages/setting/setting_list_item.dart
- lib/pages/setting/setting_logout_item.dart
- lib/util/formatters.dart
- pubspec.lock
- pubspec.yaml
- close #18 
カレンダーの下のリストのUIちゃんとした
- CalendarListItemWidget作った
- ちょっと18:30とかのシフトの時間入れたときに18:300とかならないか確かめたい感あるからデータ追加してくれるとありがたいかも
Before | After
:--: | :--:
チェックした人：
> add CalendarListItemWidget

- lib/pages/login/login_state_controller.dart
- lib/pages/setting/setting_account_item.dart
- lib/repositories/user_repository.dart
- close #68 
- 
- 先に #69 をマージして，動作確認したい
- ログインしていない状態で先に進めてしまってもエラーが発生しないようにデフォルトデータの挿入
- 
- 
- 
- 
- 
- 
Before | After
:--: | :--:
チェックした人：
> currentUserがnullだった場合，defaultUserを返すように修正

- pubspec.lock
- pubspec.yaml
- 
- 
- 
- 
- 
- 
- 
- 
Before | After
:--: | :--:
チェックした人：
> versionの指定を1.20.0に互換性があるものがあれば，よくするバージョン指定

- lib/repositories/interfaces/shift_request_repository_interface.dart
- lib/repositories/mocks/shift_request_repository_mock.dart
- lib/repositories/shift_request_repository.dart
- close #14 
- 
ShiftRepositoryをもとに，ShiftRequestRepositoryの作成
- 
- 
- 
- 
- 
- 
Before | After
:--: | :--:
チェックした人：
> ShiftRequestRepositoryの作成

- lib/debug_views/debug_page.dart
- lib/debug_views/globals.dart
- lib/debug_views/test_data.dart
- lib/repositories/interfaces/user_repository_interface.dart
- lib/repositories/mocks/user_repository_mock.dart
- lib/repositories/organization_repository.dart
- lib/repositories/user_repository.dart
- 
- 
- 
- 
- 
- 
- 
- 
Before | After
:--: | :--:
チェックした人：
> testdataを楽ちん挿入

- lib/pages/setting/setting_account_item.dart
- lib/pages/user/user_page.dart
- 
- 
とりあえず，大枠だけ作って遷移するだけ，
レイアウトとか，編集の仕方は後々考えるかここで議論したき
- 
- 
- 
- 
- 
- 
Before | After
:--: | :--:
チェックした人：
> user pageの追加

- .github/workflows/review_request_notification.yml
- 
- 
レビュワーにN人入れたらN回通知が来るやつを修正したい．
- 
- 
- 
- 
- 
- 
Before | After
:--: | :--:
チェックした人：
> [ci skip]reviewの通知がトリガーされるタイミングを変更

- lib/pages/calendar/widgets/calendar_widget.dart
- #38 
- 
- 
Before | After
:--: | :--:
チェックした人：
> feat: カレンダーのデザインを改良

- .github/workflows/test_and_build.yml
- 
- 
- 
- 
- 
- 
- 
- 
Before | After
:--: | :--:
チェックした人：
> pod install の結果をcacheする．

- lib/pages/calendar/widgets/calendar_list_item_widget.dart
- close #65 
-
-
-
-
-
-
-
owner@example.comでログインしたときの図
| <img src="" width="300" /> | <img src="https://user-images.githubusercontent.com/15919309/93873248-5f634e80-fd0c-11ea-8abe-b940675df7b4.png" width="300" /> |
チェックした人：
> 自分のシフトに色をつけた

- lib/models/models.dart
- lib/models/organization/organization.dart
- lib/models/organization/organization.freezed.dart
- lib/models/organization/organization.g.dart
- lib/models/personnel/personnel.dart
- lib/models/personnel/personnel.freezed.dart
- lib/models/personnel/personnel.g.dart
- #98｜組織の設定画面に，基本要員を設定する機能を追加
-
設定画面などは，作業がコンフリクトするのでとりあえず，モデルの作成だけ，
-
-
-
-
-
-
チェックした人：
> 組織の基本要員のモデル作成

- .github/workflows/test_and_build.yml
> fix ios build workflow

- lib/pages/setting/setting_account_item.dart
- lib/pages/user/user_page.dart
- lib/pages/user/user_state.dart
- lib/pages/user/user_state.freezed.dart
- lib/pages/user/user_state_controller.dart
- #127 
できるようにはなって，currentUserがnullのとき作成できないようにUserStateControllerの中でやってるんだけど，なぜかログインしなくてもcurrentUserが入ってて作成できてしまう．
アンインストールしてからも同じ．
それを今かまちゃんがなおしてくれてるからそれ直したあとにマージしたい
-
-
-
-
-
-
チェックした人：
> UserPageで組織新規作成できるようにした

- README.md
-
-
flutter anlyzeとflutter formatをコミット前に実行するやつのインストール方法を記載
-
-
-
-
-
-
チェックした人：
> [ci skip]pre-commitのインストール方法の記載

- lib/debug_views/debug_page.dart
- lib/debug_views/organization_dialog.dart
- lib/debug_views/shift_dialog.dart
- lib/debug_views/test_data.dart
- lib/debug_views/user_dialog.dart
- lib/pages/calendar/calendar_state_controller.dart
- lib/pages/calendar/widgets/calendar_list_item_widget.dart
- lib/pages/calendar/widgets/calendar_list_widget.dart
- lib/pages/login/login_state_controller.dart
- lib/pages/member/member_detail.dart
- lib/pages/member/member_item.dart
- lib/pages/setting/announcement_list/announcement_state_controller.dart
- lib/pages/setting/setting_account_item.dart
- lib/pages/setting/setting_org/setting_org_state_controller.dart
- lib/pages/user/user_page.dart
- lib/pages/user/user_state_controller.dart
- lib/pages/user/widgets/org_select_widget.dart
- lib/util/logger.dart
- pubspec.lock
- pubspec.yaml
- #140 
-
- debugPrintなどをしていた部分をlogger.infoなどで置き換えた
- 今後は，なるべくloggerを使うように，
-
-
-
-
チェックした人：
> migrate to simple_logger

- lib/pages/setting/setting_org/setting_org_page.dart
- lib/pages/setting/setting_org/setting_org_state.dart
- lib/pages/setting/setting_org/setting_org_state.freezed.dart
- lib/pages/setting/setting_org/setting_org_state_controller.dart
- lib/pages/setting/setting_org/widgets/setting_regular_holiday_dialog.dart
- close #96 
-
-
-
-
-
-
-
チェックした人：
> 定休日の追加削除できるようにした

- lib/main.dart
- lib/pages/calendar/calendar_page.dart
- lib/pages/calendar/widgets/calendar_list_item_widget.dart
- lib/pages/calendar/widgets/calendar_list_widget.dart
- lib/pages/calendar/widgets/calendar_shift_request_widget.dart
- lib/pages/calendar/widgets/calendar_widget.dart
- lib/pages/login/login_page.dart
- lib/pages/member/member_detail.dart
- lib/pages/member/member_item.dart
- lib/pages/setting/announcement_list/announcement_list_page.dart
- lib/pages/setting/setting_account_item.dart
- lib/pages/setting/setting_logout_item.dart
- lib/pages/user/user_page.dart
- lib/pages/user/widgets/org_select_widget.dart
- close #143 
-
Provider.ofでアクセスしていた部分を必要に応じて，`context.select`や`context.read`に置き換えた．
-
-
-
-
-
-
チェックした人：
> replace Provider.of to context.select or context.read

- lib/debug_views/test_data.dart
- lib/repositories/shift_repository.dart
- lib/repositories/shift_request_repository.dart
> shiftをDBからモデルに変換するところの修正

- .github/workflows/test_and_build.yml
- README.md
> apkファイルをdeploygateにpushするGithubActionsの追加

- build.yaml
- lib/models/announcement/announcement.g.dart
- lib/models/holiday/holiday.g.dart
- lib/models/member/member.g.dart
- lib/models/organization/organization.g.dart
- lib/models/personnel/personnel.g.dart
- lib/models/shift/shift.g.dart
- lib/models/user/user.g.dart
- lib/pages/setting/announcement_list/announcement_list_state.dart
-
-
build.yamlを置いて，generateするときのファイルを絞ることで速度を上げた
参考 [monoさんのtweet](https://twitter.com/_mono/status/1284299309647724544?s=20)
-
-
-
-
-
-
チェックした人：
> make generateの最適化

- lib/pages/calendar/calendar_state_controller.dart
- close #156
-
-
-
-
-
-
-
チェックした人：
> 起動時のエラーを修正

- .github/workflows/test_and_build.yml
-
-
github.event.head_commit.urlでコミットのurl
github.refでブランチ名
-
-
-
-
-
-
チェックした人：
> デプロイゲートにデプロイされたバージョンがどのrevisionのものなのかわかるように修正

- .fvm/fvm_config.json
- .gitignore
-
-
https://qiita.com/Slowhand0309/items/0767abee120fcb3ba0b4
https://qiita.com/Kurusu_ima/items/2dfd067f6e79f520198f
-
-
-
-
-
-
チェックした人：
> fvmに対応させていい感じにバージョンを切り替えれるようにした．

- .github/workflows/test_and_build.yml
- README.md
-
-
READMEにあるインストールボタンの修正
アプリのメッセージからbuild時のコミットに飛べるように修正;wq
-
-
-
-
-
-
チェックした人：
> deploy gate周りの調整

- .fvm/fvm_config.json
- .github/workflows/test_and_build.yml
- lib/main.dart
- lib/models/announcement/announcement.freezed.dart
- lib/models/holiday/holiday.freezed.dart
- lib/models/member/member.freezed.dart
- lib/models/organization/organization.freezed.dart
- lib/models/personnel/personnel.freezed.dart
- lib/models/shift/shift.freezed.dart
- lib/models/user/user.freezed.dart
- lib/pages/calendar/calendar_state.freezed.dart
- lib/pages/calendar/widgets/calendar_list_tab_widget.dart
- lib/pages/calendar/widgets/calendar_widget.dart
- lib/pages/login/login_state.freezed.dart
- lib/pages/member/member_state.freezed.dart
- lib/pages/setting/announcement/announcement_page.dart
- lib/pages/setting/announcement_list/announcement_list_page.dart
- lib/pages/setting/announcement_list/announcement_list_state.freezed.dart
- lib/pages/setting/setting_org/setting_org_state.freezed.dart
- lib/pages/setting/setting_org/widgets/setting_default_personnel_dialog.dart
- lib/pages/user/user_state.freezed.dart
- pubspec.lock
- pubspec.yaml
> Chore/bump flutter version to 1.22.0

- ios/Podfile
- ios/Podfile.lock
-
-
build targetのバージョンでめちゃくちゃワーニング言ってたのを処理した．
脳死でもいいけど，
iosでビルドできるか確認してもらったほうが良いかも？
-
-
-
-
-
-
チェックした人：
> flutter build ios したときのwarningを処理
